// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzbtblrueinmthhxelzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6YnRibHJ1ZWlubXRoaHhlbHpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDc3MjIsImV4cCI6MjA2OTEyMzcyMn0.wsHe1nsZKjdlTP2vLE-Mhupp90Ls_lU0XHR8Ap2Bmjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});